apiVersion: v1
kind: Service
metadata:
  name: smart-home-service
spec:
  type: NodePort
  selector:
    app: smart-home
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000